[versions]
androidApplication = "8.6.0"
jetbrainsKotlinAndroid = "1.9.0"
coreKtx = "1.10.1"
junit = "4.13.2"
androidxJunit = "1.1.5"
espressoCore = "3.5.1"
appcompat = "1.6.1"
material = "1.9.0"
dataStore = "1.1.1"
lifecycleProcess = "2.10.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-datastore = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "dataStore" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycleProcess" }

[plugins]
android-application = { id = "com.android.application", version.ref = "androidApplication" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "jetbrainsKotlinAndroid" }
